version: '2'

services:
  teamspeak:
    restart: always
    image: mbentley/teamspeak
    ports:
    - 9987:9987/udp
    - 30033:30033
    - 10011:10011
    - 41144:41144
    volumes:
    - teamspeak-data:/data

