version: '2'

services:
  nexus:
    image: sonatype/nexus3
    ports:
     - "7071:8081"
     - "18079:18079"
    volumes:
    - nexus-data:/nexus-data
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:host_label: hostname=${rancher_host}

volumes:
  nexus-data:
    driver: rancher-nfs
    external: true


