version: '2'

services:
  splunk:
    hostname: splunk
    image: splunk/splunk:6.6.3
    environment:
      SPLUNK_START_ARGS: --accept-license
      SPLUNK_ENABLE_LISTEN: 9997
      SPLUNK_ADD: tcp 1514
    volumes:
      - splunk-etc:/opt/splunk/etc
      - splunk-var:/opt/splunk/var
    ports:
      - "9997:9997"

volumes:
  splunk-etc:
    driver: rancher-nfs
    external: true
  splunk-var:
    driver: rancher-nfs
    external: true
