version: '2'

services:
  splunk:
    hostname: splunk
    image: splunk/splunk:latest
    environment:
      SPLUNK_START_ARGS: --accept-license --answer-yes
      SPLUNK_ENABLE_LISTEN: 9997
      SPLUNK_ADD: tcp 1514
    volumes:
      - splunk-etc:/opt/splunk/etc
      - splunk-var:/opt/splunk/var
    ports:
      - "9997:9997"
      - "9092:8000"
    labels:
      io.rancher.scheduler.affinity:host_label: hostname=neptune

volumes:
  splunk-etc:
    driver: rancher-nfs
    external: true
  splunk-var:
    driver: rancher-nfs
    external: true
