version: '2'

services:
  postgresql:
    restart: always
    image: sameersbn/postgresql:9.6-2
    ports:
      - "5432:5432"
    environment:
      - DEBUG=false
      - DB_USER=gitlab
      - DB_PASS=gitlab
      - DB_NAME=gitlab
      - DB_TEMPLATE=

      - DB_EXTENSION=pg_trgm

      - REPLICATION_MODE=
      - REPLICATION_USER=
      - REPLICATION_PASS=
      - REPLICATION_SSLMODE=
    volumes:
      - postgres-data:/var/lib/postgresql
    labels:
      io.rancher.scheduler.affinity:host_label: hostname=deimos

volumes:
  postgres-data:
    driver: rancher-nfs
    external: true