version: "2"

services:
  mesos-master:
    image: mesosphere/mesos-slave:1.3.0
    volumes:
      - mesos-slave-1:/var/tmp/mesos
      - /var/run/docker.sock:/var/run/docker.sock
      - /cgroup:/cgroup
      - /sys:/sys
      - /usr/local/bin/docker:/usr/local/bin/docker
    environment:
      MESOS_PORT: 5051
      MESOS_MASTER: ${mesos_master}
      MESOS_SWITCH_USER: 0
      MESOS_CONTAINERIZERS: mesos,docker
      MESOS_LOG_DIR: /var/log/mesos
      MESOS_WORK_DIR: /var/tmp/mesos
    network_mode: "host"
    privileged: true
    labels:
      io.rancher.container.pull_image: always

volumes:
  mesos-slave-1:
    driver: rancher-nfs
    external: true