version: '2'

services:

  gitlab:
    restart: always
    image: gitlab/gitlab-ce:latest
    ports:
      - "10080:80"
      - "10022:22"
    environment:
      - GITLAB_OMNIBUS_CONFIG="external_url '${external_url}'; postgresql['shared_buffers'] = '256MB'"
    volumes:
      - gitlab-data:/var/opt/gitlab
      - gitlab-config:/etc/gitlab
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:host_label: hostname=${rancher_host}

volumes:
  gitlab-data:
    driver: rancher-nfs
    external: true
  gitlab-config:
    driver: rancher-nfs
    external: true
