version: '2'

services:
  dokuwiki:
    image: bitnami/dokuwiki:latest
    volumes:
      - dokuwiki-data:/bitnami
    environment:
      DOKUWIKI_WIKI_NAME: The Webster Wiki
    ports:
      - "9500:80"
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:host_label: hostname=${rancher_host}

volumes:
  dokuwiki-data:
    driver: rancher-nfs