version: '2'

services:
  sonarqube:
    image: sonarqube:latest
    links:
      - postgres
    environment:
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
      SONARQUBE_JDBC_USERNAME: ${postgres_user}
      SONARQUBE_JDBC_PASSWORD: ${postgres_password}
      SONARQUBE_JDBC_URL: jdbc:postgresql://postgres/sonar
    labels:
      io.rancher.container.pull_image: always

  postgres:
    image: postgres:latest
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: ${postgres_db}
      POSTGRES_USER: ${postgres_user}
      POSTGRES_PASSWORD: ${postgres_password}
    tty: true
    stdin_open: true
    volumes:
      - sonarqube-px-data:/var/lib/postgresql/data/pgdata
    labels:
      io.rancher.container.pull_image: always

volumes:
  sonarqube-px-data:
    driver: pxd
    driver_opts:
      repl: '3'
      size: '5'
