version: "2"

services:
  logspout:
    image: gliderlabs/logspout:v3.3-dev
    command: syslog+tcp://${external_hostname}?filter.labels=${filter_labels}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  oklog-1:
    image: oklog/oklog
    command: 'ingeststore -debug -store.segment-replication-factor 3 -cluster oklog-1 -peer oklog-1 -peer oklog-2 -peer oklog-3'
    volumes:
      - oklog-data-px-1:/data
    labels:
      io.rancher.scheduler.affinity:container_label_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}

  oklog-2:
    image: oklog/oklog
    command: 'ingeststore -debug -store.segment-replication-factor 3 -cluster oklog-2 -peer oklog-1 -peer oklog-2 -peer oklog-3'
    volumes:
      - oklog-data-px-2:/data
    labels:
        io.rancher.scheduler.affinity:container_label_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}

  oklog-3:
    image: oklog/oklog
    command: 'ingeststore -debug -store.segment-replication-factor 3 -cluster oklog-3 -peer oklog-1 -peer oklog-2 -peer oklog-3'
    volumes:
      - oklog-data-px-3:/data
    labels:
      io.rancher.scheduler.affinity:container_label_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}

volumes:
  oklog-data-px-1:
    driver: pxd
    driver_opts:
      repl: '3'
      size: '5'
  oklog-data-px-2:
    driver: pxd
    driver_opts:
      repl: '3'
      size: '5'
  oklog-data-px-3:
    driver: pxd
    driver_opts:
      repl: '3'
      size: '5'