.catalog:
  name: OK Log (with Logspout)
  version: latest
  description: Distributed Log Management System
  questions:
  - variable: container_names
    description: "Container Names to include"
    label: "Container Names"
    required: true
    type: "string"