version: "2"

services:
  mesos-master:
    image: mesosphere/mesos-master:1.3.0
    volumes:
      - mesos-master:/var/tmp/mesos
    environment:
      MESOS_PORT: 5050
      MESOS_QUORUM: 1
      MESOS_REGISTRY: in_memory
      MESOS_LOG_DIR: /var/log/mesos
      MESOS_WORK_DIR: /var/tmp/mesos
    network_mode: "host"
    labels:
      io.rancher.container.pull_image: always

volumes:
  mesos-master:
    driver: rancher-nfs
    external: true