version: "2"

services:
  mesos-master:
    image: mesosphere/mesos-master:1.3.0
    volumes:
      - mesos-master:/var/tmp/mesos
    environment:
      MESOS_HOSTNAME: mars
      MESOS_PORT: 5050
      MESOS_QUORUM: 1
      MESOS_REGISTRY: in_memory
      MESOS_LOG_DIR: /var/log/mesos
      MESOS_WORK_DIR: /var/tmp/mesos/master
    #  GLOG_v: 3
    labels:
      io.rancher.container.pull_image: always

  mesos-slave:
    image: mesosphere/mesos-slave:1.3.0
    volumes:
      - mesos-slave-1:/var/tmp/mesos
      - /var/run/docker.sock:/var/run/docker.sock
      - /cgroup:/cgroup
      - /sys:/sys
      - /usr/local/bin/docker:/usr/local/bin/docker
    environment:
      MESOS_PORT: 5051
      MESOS_MASTER: mesos-master:5050
      MESOS_SWITCH_USER: 0
      MESOS_CONTAINERIZERS: mesos,docker
      MESOS_LOG_DIR: /var/log/mesos
      MESOS_WORK_DIR: /var/tmp/mesos
      MESOS_LAUNCHER:  posix
    privileged: true
    labels:
      io.rancher.container.pull_image: always

  jenkins:
      image: localhost:5000/timw/jenkins
      volumes:
        - jenkins-data:/var/jenkins_home
      environment:
        JENKINS_SLAVE_AGENT_PORT: 50000
    #    GLOV_v: 3
      labels:
        io.rancher.container.pull_image: always

volumes:
  mesos-master:
    driver: rancher-nfs
    external: true
  mesos-slave-1:
    driver: rancher-nfs
    external: true
  jenkins-data:
    driver: rancher-nfs
    external: true