.catalog:
  name: Jenkins
  version: latest
  description: |
    Jenkins CI management server.
  questions:
  - variable: "jnlp_host_port"
    type: "int"
    label: "JNLP Host Port Number"
    description: "Port for Jenkins slaves to expose on host"
    default: 50001
    required: true
  - variable: "plugins"
    type: "multiline"
    label: "List of Plugins"
    description: |
      List of plugins in the format <plugin_name>[:<version>]
      one entry per line.
    default: |
      credentials
      git
      git-client
      github
      github-api
      github-oauth
      greenballs
      junit
      plain-credentials
      scm-api
      ssh-credentials
      ssh-slaves
      swarm
jenkins:
  metadata:
    plugins: |
      ${plugins}
