version: '2'

services:

  gitlab:
    restart: always
    image: gitlab/gitlab-ce
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url '${external_url}'
        postgresql['shared_buffers'] = "256MB"
        unicorn['worker_processes'] = 2
    volumes:
      - gitlab-px-data:/var/opt/gitlab
    labels:
      io.rancher.container.pull_image: always

