.catalog:
  name: "Gitlab (Portworx)"
  version: "latest"
  description: "Gitlab"
  questions:
    - variable: external_url
      label: External URL
      description: External URL
      required: true
      default: "http://gitlab.portworx.zone"
      type: string
