version: "2"
services:
  server:
    image: registry.rancher.zone/timw/notary-server:latest
    command: "-config=/config/server-config.json"
    depends_on:
      - server-db
      - signer

  server-db:
    image: registry.rancher.zone/timw/notary-server-db:latest
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD="yes"
    volumes:
      - notary-server-data:/var/lib/mysql

  signer:
    image: registry.rancher.zone/timw/notary-signer:latest
    command: "-config=/config/signer-config.json"
    environment:
      NOTARY_SIGNER_PASSWORDALIAS1=mypassword
    depends_on:
      - signer-db
      
  signer-db:
    image: registry.rancher.zone/timw/notary-signer-db:latest
    volumes:
      - notary-signer-data:/var/lib/mysql

volumes:
  notary-server-data:
    driver: rancher-nfs
    external: true
  notary-signer-data:
    driver: rancher-nfs
    external: true
