version: "2"
services:
  notaryserver:
    image: registry.rancher.zone/timw/notary-server:latest
    command: "-config=/config/server-config.json"
    depends_on:
      - server-db
      - signer
    labels:
      io.rancher.container.pull_image: always

  server-db:
    image: registry.rancher.zone/timw/notary-server-db:latest
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD="yes"
#    volumes:
#      - notary-server-data:/var/lib/mysql
    labels:
      io.rancher.container.pull_image: always

  notarysigner:
    image: registry.rancher.zone/timw/notary-signer:latest
    command: "-config=/config/signer-config.json"
    environment:
      - NOTARY_SIGNER_PASSWORDALIAS1=mypassword
    depends_on:
      - signer-db
    labels:
      io.rancher.container.pull_image: always

  signer-db:
    image: registry.rancher.zone/timw/notary-signer-db:latest
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD="yes"
#    volumes:
#      - notary-signer-data:/var/lib/mysql
    labels:
      io.rancher.container.pull_image: always
      
#volumes:
#  notary-server-data:
#    driver: rancher-nfs
#    external: true
#  notary-signer-data:
#    driver: rancher-nfs
#    external: true
