version: '2'

services:
  bind:
    restart: always
    image: sameersbn/bind:9.9.5-20161106
    ports:
    - 53:53/udp
    - 53:53/tcp
    - ${webmin_port}:10000
    volumes:
    - bind-data:/data

volumes:
  bind-data:
    driver: rancher-nfs
    external: true