version: "2"

services:
  logspout:
    image: gliderlabs/logspout:v3.3-dev
    command: syslog+tcp://oklog:7651?filter.labels=${filter_labels}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      io.rancher.scheduler.global: true

  oklog:
    image: oklog/oklog
    command: 'ingeststore -store.segment-replication-factor 1'
    volumes:
      - oklog-data:/data

volumes:
  oklog-data:
    driver: rancher-nfs
    external: true
