version: '2'

services:
  squid:
    image: localhost:5000/timw/squid
    ports:
      - ${http_port}:3128
    volumes:
      - squid-data:/data
    labels:
      io.rancher.container.pull_image: always

volumes:
  squid-data:
    driver: rancher-nfs
    external: true
