version: '2'

services:
  squid:
    image: mars:5000/timw/squid
    ports:
      - ${http_port}:3128
    volumes:
      - squid-data:/data

volumes:
  squid-data:
    driver: rancher-nfs
    external: true
