version: '2'

services:
  artifactory:
    image: docker.bintray.io/jfrog/artifactory-oss:latest
    volumes:
      - artifactory-data:/var/opt/jfrog/artifactory
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:host_label: hostname=${rancher_host}

volumes:
  artifactory-data:
    driver: rancher-nfs
    external: true

