version: '2'

services:
  splunk:
    hostname: splunk
    image: splunk/splunk:6.6.3
    environment:
      SPLUNK_START_ARGS: --accept-license
      SPLUNK_ENABLE_LISTEN: 9997
      SPLUNK_ADD: tcp 1514
    volumes:
      - splunk-uf-etc:/opt/splunk/etc
      - splunk-uf-var:/opt/splunk/var

volumes:
  splunk-uf-etc:
    driver: rancher-nfs
    external: true
  splunk-uf-var:
    driver: rancher-nfs
    external: true
