version: '2'

services:
  splunk:
    hostname: splunk
    image: splunk/universalforwarder:6.6.3
    environment:
      SPLUNK_START_ARGS: --accept-license --answer-yes
      SPLUNK_ENABLE_LISTEN: 9997
      SPLUNK_FORWARD_SERVER: splunk.rancher.zone:9997
      SPLUNK_ADD: tcp 1514
      SPLUNK_ADD_1: monitor /mesos-logs/master -host deimos -sourcetype mesos-master-logs
      SPLUNK_ADD_2: monitor /mesos-logs/slave -host deimos -sourcetype mesos-slave-logs
      SPLUNK_ADD_3: monitor /mesos-workdir/slave -host deimos -sourcetype mesos-slave-work

    volumes:
#      - splunk-uf-etc:/opt/splunk/etc
#      - splunk-uf-var:/opt/splunk/var
      - /var/log/mesos:/mesos-logs
      - /var/lib/mesos:/mesos-workdir

    labels:
      io.rancher.scheduler.affinity:host_label: hostname=deimos

#volumes:
#  splunk-uf-etc:
#    driver: rancher-nfs
#    external: true
#  splunk-uf-var:
#    driver: rancher-nfs
#    external: true
