version: "2"

services:
  gogs:
    image: gogs/gogs
    volumes:
      - gogs-data:/data
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:host_label: hostname=mars

volumes:
  gogs-data:
    driver: rancher-nfs
    external: true
